### ISSUE TITLE
Font using em

### ISSUE THREAD

**Issue by NigelRoth** [Aymkdn/html-to-pdfmake#103]
Hi, I'm having a problem with users that include font sizes in "em"s .  The pdf aborts without creating anything
Examples
span style="font-size:1.2em;"   fred    /span
font size="1em"   fred  /font
do not work

But other sizes, such as px or pt
span style="font-size:9px;"  fred  /span
do work

Do you have a fix planned for this as Word and other doc types use em's

**Comment by Aymkdn** [comment]
I've just published the v2.2.1 that supports the `em` unit

**Comment by NigelRoth** [comment]
That’s great, thank you very much. Keep up the good work.

Regards

Nigel

**Comment by NigelRoth** [comment]
Unfortunately I've been using 2.1.2 from January because a release after that had a bug.  I know you fixed that quickly, but I didn't want to risk users seeing it when I had a working version.
So I've just tried to upgrade to 2.2.1 to fix the em, but there must be something else that you changed in between that is causing even a simple test page not to convert.

I've attached a .txt version of my .asp if that helps identify the issue and your help will be much appreciated.

[proc-html-pdf.txt](https://github.com/Aymkdn/html-to-pdfmake/files/6566005/proc-html-pdf.txt)

**Comment by NigelRoth** [comment]
![Screenshot_2021-05-30 HTML to PDFmake online convertor](https://user-images.githubusercontent.com/36405728/120100099-94e7f380-c147-11eb-8b28-ef5716e6e972.png)

Also get same problem in your playground, sorry.

**Comment by Aymkdn** [comment]
Please, provide the HTML code that you passed into the playgroud.

**Comment by NigelRoth** [comment]
As per the screen shot, I simply changed the last line to

 

<span class="green" style="font-size:1em;">

 

Changing 1em to 14px works though as before.

Nigel

**Comment by NigelRoth** [comment]
However, just noticed there is a mistake in the original code
<span class="green">Text in green using the styles from PDFMake</small>
Should end </span> but it makes no difference, adding style="font-size:1em;" still does not work.

Nigel

**Comment by Aymkdn** [comment]
Can you copy your full html code here, please? I cannot copy a text from a screenshot...

**Comment by NigelRoth** [comment]
This is the amended code of your playground. All I have done is change the last line to include the font-size, but also note that the </small> you have is wrong.

<div>
  <h1>My title</h1>
  <p>
    This is a sentence with a <strong>bold word</strong>, <em>one in italic</em>,
    and <u>one with underline</u>. And finally <a href="https://www.somewhere.com">a link</a>.
  </p>
  <table>
    <tr>
      <th style="width:150px">Header 1</th>
    </tr>
    <tr>
      <td style="text-align:center" height="50">Cell A1</td>
    </tr>
  </table>
  <span class="green" style="font-size:1em;">Text in green using the styles from PDFMake</small>
</div>

**Comment by Aymkdn** [comment]
OK I understand now. I've just published v2.2.2 that correctly support `em` this time.

**Comment by NigelRoth** [comment]
Sorry still not working in your playground with style as below and before but does work now for <font size="1em"></font> 
<div>
  <h1>My title</h1>
  <p>
    This is a sentence with a <strong>bold word</strong>, <em>one in italic</em>,
    and <u>one with underline</u>. And finally <a href="https://www.somewhere.com">a link</a>.
  </p>
  <table>
    <tr>
      <th style="width:150px">Header 1</th>
    </tr>
    <tr>
      <td style="text-align:center" height="50">Cell A1</td>
    </tr>
  </table>
  <span class="green" style="font-size:1em;">Text in green using the styles from PDFMake</span>
</div>

Unfortunately, my users are nearly always trying to insert styles not fonts (which are a bit old-fashioned).

Nigel

**Comment by Aymkdn** [comment]
The CDN version that the playground is using is not updated yet (still using previous version). It may take some time for the CDN to refresh (especially because the difference is only 1 character between the 2 versions).

By forcing it, I got the right result:
![image](https://user-images.githubusercontent.com/946315/120108363-29ad1a00-c165-11eb-99f2-9172c1c7a7a2.png)

**Comment by NigelRoth** [comment]
Sorry, still not working.

I downloaded 2.2.2 and switched the browser.js  to the new one.

Using a very simple text, there must be something else in my code which is attached but which is incompatible with another change you made between 2.1.2 and the current.

 

Nigel

**Comment by Aymkdn** [comment]
Provide the HTML code you're using. Without it I cannot help.

**Comment by NigelRoth** [comment]
I attached a txt file to the last email with the code. But here it is in the body.

 

 

<!doctype html>

<html lang='en'>

<head>

<meta charset='utf-8'>

<title>PDF Download</title>



<script ***@***.***/build/pdfmake.min.js ***@***.***/build/pdfmake.min.js>'></script>

<script ***@***.***/build/vfs_fonts.min.js ***@***.***/build/vfs_fonts.min.js>'></script>

 

<script src='../assets/browser_2.2.2.js <view-source:https://propertyclubinternational.com/assets/browser_2.2.2.js>'></script>

 

 

</head>

<body>

<script>

    var subject = htmlToPdfmake('Test');

    var heading = htmlToPdfmake('');

    var dt = htmlToPdfmake('22 May 2021 12:00');

    var article = htmlToPdfmake('<p><span style="font-size:1em;">test</span></p>');

    var desc = htmlToPdfmake('');

           

                     var dd = {

                     watermark: {text: 'British Residents Society', color: 'blue', opacity: 0.1},

                     content: [ 

                     {image: 'logo', width: 200},

                     {text: '\n'},

                     {text: subject+' '+dt,style: ['blue']},

                     {text: heading,style: ['blue']},

 

                     {text: '\n'},

                     

                     article,

                     

                     desc,

                     

                     ],

 

                     images: {

                                logo: 'https://propertyclubinternational.com/images/brs_logo.jpg',

                                

                                },

                     styles:{ 

                                blue:{ color:'blue', bold: true }

                                },

                     pageBreakBefore: function(currentNode) {

                                return currentNode.style && currentNode.style.indexOf('pdf-pagebreak-before') > -1;

                                }

                     };

           

 

    pdfMake.createPdf(dd).download();

</script>

<div id="container" >

    <h1>Your PDF will download shortly</h1>

    

</div>

 

</body>

</html>

**Comment by Aymkdn** [comment]
OK, it's an issue introduced with v2.2.0 when a TAG is not formally supported.

I've just published v2.2.3

**Comment by Aymkdn** [comment]
And, please, stop using emails, but post directly on Github: https://github.com/Aymkdn/html-to-pdfmake/issues/103

**Comment by NigelRoth** [comment]
Your help is really appreciated, and I will post on Github in future although still getting used to inserting code.
Looks like by TAG you mean html lang="en" but I will try again with 2.2.3 tomorrow and let you know.
Many thanks
Nigel

**Comment by NigelRoth** [comment]
Thanks, that is working now. Sorry if it took a little while to get there.
